### ISSUE TITLE
Why Java result and PHP result different?

### ISSUE THREAD

**Issue by jeok70** [0xbb/php-sha3#1]
Why Java result and PHP result different 

There length is setting SHA3-224 the Java code that URL
https://gist.github.com/jeok70/ff62b90e703a054d4df4
SHA3-224 result : (Input:"123")
PHP : 602bdc204140db016bee5374895e5568ce422fabe17e064061d80097
JAVA: 5c52615361ce4c5469f9d8c90113c7a543a4bf43490782d291cb32d8

**Comment by 0xbb** [comment]
I think it’s, because of the the difference between Keccak vs SHA3
I tested with this implementation:
https://emn178.github.io/online-tools/sha3_224.html is giving: 602bdc204140db016bee5374895e5568ce422fabe17e064061d80097
https://emn178.github.io/online-tools/keccak_224.html : 5c52615361ce4c5469f9d8c90113c7a543a4bf43490782d291cb32d8

**Comment by jeok70** [comment]
Thanke you so Keccak vs SHA3 Why difference?
this php is not found Keccak, is find SHA3
My project Sever is PHP  Client is java 
How to fix problem?

**Comment by 0xbb** [comment]
The original Keccack uses a different padding than SHA3.
I would switch to a different SHA3 implementation for Java.

This is where my support ends.

**Comment by jeok70** [comment]
My Project is Complete

**Comment by jeok70** [comment]
Thank you
